[package]
name = "tds"
version = "0.0.1"
authors = ["LFalch <lucas@wasd.dk>"]

[dependencies]
ggez = "0.4"
bincode = "~1"
serde_derive = "~1"
serde = "~1"
self-compare = "0.2"
sdl2 = "0.31"
rand = "0.4"

[profile.dev]
opt-level = 2

[profile.doc]
opt-level = 2

[profile.test]
opt-level = 2

[profile.release]
lto = true
